In [1]:
# Dependencies
import os
import json
import pandas as pd
import requests as req
import matplotlib.pyplot as plt
import numpy as np
import datetime
import dateutil
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

## Alpha Vantage

In [2]:
from alpha import api_key

In [3]:
alpha_url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=api_key"

In [4]:
stock_data=req.get(alpha_url).json()

In [5]:
print(json.dumps(stock_data, indent = 4, sort_keys=True))

{
    "Meta Data": {
        "1. Information": "Daily Prices (open, high, low, close) and Volumes",
        "2. Symbol": "MSFT",
        "3. Last Refreshed": "2018-08-30 16:00:01",
        "4. Output Size": "Compact",
        "5. Time Zone": "US/Eastern"
    },
    "Time Series (Daily)": {
        "2018-04-11": {
            "1. open": "92.0100",
            "2. high": "93.2900",
            "3. low": "91.4800",
            "4. close": "91.8600",
            "5. volume": "24872110"
        },
        "2018-04-12": {
            "1. open": "92.4300",
            "2. high": "94.1600",
            "3. low": "92.4300",
            "4. close": "93.5800",
            "5. volume": "26758879"
        },
        "2018-04-13": {
            "1. open": "94.0500",
            "2. high": "94.1800",
            "3. low": "92.4400",
            "4. close": "93.0800",
            "5. volume": "23346063"
        },
        "2018-04-16": {
            "1. open": "94.0700",
            "2. high": "94.6600",
            "3. low": "93.4200",
            "4. close": "94.1700",
            "5. volume": "20288083"
        },
        "2018-04-17": {
            "1. open": "95.0000",
            "2. high": "96.5400",
            "3. low": "94.8800",
            "4. close": "96.0700",
            "5. volume": "26771000"
        },
        "2018-04-18": {
            "1. open": "96.2200",
            "2. high": "96.7200",
            "3. low": "95.5200",
            "4. close": "96.4400",
            "5. volume": "21043287"
        },
        "2018-04-19": {
            "1. open": "96.4400",
            "2. high": "97.0700",
            "3. low": "95.3400",
            "4. close": "96.1100",
            "5. volume": "23552541"
        },
        "2018-04-20": {
            "1. open": "95.9100",
            "2. high": "96.1100",
            "3. low": "94.0500",
            "4. close": "95.0000",
            "5. volume": "31154377"
        },
        "2018-04-23": {
            "1. open": "95.7436",
            "2. high": "96.2900",
            "3. low": "94.6300",
            "4. close": "95.3500",
            "5. volume": "22331829"
        },
        "2018-04-24": {
            "1. open": "96.2420",
            "2. high": "96.4700",
            "3. low": "92.4100",
            "4. close": "93.1200",
            "5. volume": "34524799"
        },
        "2018-04-25": {
            "1. open": "93.3000",
            "2. high": "93.3000",
            "3. low": "90.2800",
            "4. close": "92.3100",
            "5. volume": "33729257"
        },
        "2018-04-26": {
            "1. open": "93.5500",
            "2. high": "95.1500",
            "3. low": "93.1000",
            "4. close": "94.2600",
            "5. volume": "42529043"
        },
        "2018-04-27": {
            "1. open": "97.6000",
            "2. high": "97.9000",
            "3. low": "93.9100",
            "4. close": "95.8200",
            "5. volume": "48272780"
        },
        "2018-04-30": {
            "1. open": "96.3300",
            "2. high": "96.3964",
            "3. low": "93.1500",
            "4. close": "93.5200",
            "5. volume": "41523605"
        },
        "2018-05-01": {
            "1. open": "93.2100",
            "2. high": "95.2900",
            "3. low": "92.7900",
            "4. close": "95.0000",
            "5. volume": "31408927"
        },
        "2018-05-02": {
            "1. open": "94.9900",
            "2. high": "95.1700",
            "3. low": "93.1900",
            "4. close": "93.5100",
            "5. volume": "27471002"
        },
        "2018-05-03": {
            "1. open": "92.9600",
            "2. high": "94.9250",
            "3. low": "92.4500",
            "4. close": "94.0700",
            "5. volume": "31142497"
        },
        "2018-05-04": {
            "1. open": "93.3200",
            "2. high": "95.3700",
            "3. low": "92.9200",
            "4. close": "95.1600",
            "5. volume": "22531325"
        },
        "2018-05-07": {
            "1. open": "95.1700",
            "2. high": "96.7100",
            "3. low": "95.1000",
            "4. close": "96.2200",
            "5. volume": "24242019"
        },
        "2018-05-08": {
            "1. open": "95.8456",
            "2. high": "96.1600",
            "3. low": "95.0631",
            "4. close": "95.8100",
            "5. volume": "23484589"
        },
        "2018-05-09": {
            "1. open": "96.0100",
            "2. high": "96.9700",
            "3. low": "95.0500",
            "4. close": "96.9400",
            "5. volume": "27327410"
        },
        "2018-05-10": {
            "1. open": "97.4600",
            "2. high": "97.9500",
            "3. low": "97.0500",
            "4. close": "97.9100",
            "5. volume": "22388119"
        },
        "2018-05-11": {
            "1. open": "97.8000",
            "2. high": "97.8700",
            "3. low": "97.0400",
            "4. close": "97.7000",
            "5. volume": "16778316"
        },
        "2018-05-14": {
            "1. open": "97.9200",
            "2. high": "98.6900",
            "3. low": "97.3100",
            "4. close": "98.0300",
            "5. volume": "19454124"
        },
        "2018-05-15": {
            "1. open": "97.2400",
            "2. high": "97.8500",
            "3. low": "96.3400",
            "4. close": "97.3200",
            "5. volume": "24594010"
        },
        "2018-05-16": {
            "1. open": "97.3600",
            "2. high": "97.4000",
            "3. low": "96.6150",
            "4. close": "97.1500",
            "5. volume": "17384742"
        },
        "2018-05-17": {
            "1. open": "96.7600",
            "2. high": "97.5401",
            "3. low": "95.8300",
            "4. close": "96.1800",
            "5. volume": "17246716"
        },
        "2018-05-18": {
            "1. open": "96.0100",
            "2. high": "96.9300",
            "3. low": "96.0100",
            "4. close": "96.3600",
            "5. volume": "17865840"
        },
        "2018-05-21": {
            "1. open": "97.0000",
            "2. high": "98.0100",
            "3. low": "96.8000",
            "4. close": "97.6000",
            "5. volume": "19422467"
        },
        "2018-05-22": {
            "1. open": "97.6800",
            "2. high": "98.1700",
            "3. low": "97.2000",
            "4. close": "97.5000",
            "5. volume": "15441189"
        },
        "2018-05-23": {
            "1. open": "96.7100",
            "2. high": "98.7300",
            "3. low": "96.3200",
            "4. close": "98.6600",
            "5. volume": "21251222"
        },
        "2018-05-24": {
            "1. open": "98.7250",
            "2. high": "98.9400",
            "3. low": "96.8100",
            "4. close": "98.3100",
            "5. volume": "26649287"
        },
        "2018-05-25": {
            "1. open": "98.3000",
            "2. high": "98.9800",
            "3. low": "97.8600",
            "4. close": "98.3600",
            "5. volume": "18363918"
        },
        "2018-05-29": {
            "1. open": "97.8400",
            "2. high": "98.8800",
            "3. low": "97.2300",
            "4. close": "98.0100",
            "5. volume": "28670981"
        },
        "2018-05-30": {
            "1. open": "98.3100",
            "2. high": "99.2500",
            "3. low": "97.9100",
            "4. close": "98.9500",
            "5. volume": "22158528"
        },
        "2018-05-31": {
            "1. open": "99.2900",
            "2. high": "99.9900",
            "3. low": "98.6100",
            "4. close": "98.8400",
            "5. volume": "34140891"
        },
        "2018-06-01": {
            "1. open": "99.2798",
            "2. high": "100.8600",
            "3. low": "99.1700",
            "4. close": "100.7900",
            "5. volume": "28655624"
        },
        "2018-06-04": {
            "1. open": "101.2600",
            "2. high": "101.8600",
            "3. low": "100.8510",
            "4. close": "101.6700",
            "5. volume": "27281623"
        },
        "2018-06-05": {
            "1. open": "102.0000",
            "2. high": "102.3300",
            "3. low": "101.5300",
            "4. close": "102.1900",
            "5. volume": "23514402"
        },
        "2018-06-06": {
            "1. open": "102.4800",
            "2. high": "102.6000",
            "3. low": "101.9000",
            "4. close": "102.4900",
            "5. volume": "21122917"
        },
        "2018-06-07": {
            "1. open": "102.6500",
            "2. high": "102.6900",
            "3. low": "100.3800",
            "4. close": "100.8800",
            "5. volume": "28232197"
        },
        "2018-06-08": {
            "1. open": "101.0924",
            "2. high": "101.9500",
            "3. low": "100.5400",
            "4. close": "101.6300",
            "5. volume": "22165128"
        },
        "2018-06-11": {
            "1. open": "101.3700",
            "2. high": "101.5900",
            "3. low": "100.6700",
            "4. close": "101.0500",
            "5. volume": "23490894"
        },
        "2018-06-12": {
            "1. open": "101.1000",
            "2. high": "101.4493",
            "3. low": "100.7500",
            "4. close": "101.3100",
            "5. volume": "18325228"
        },
        "2018-06-13": {
            "1. open": "101.7200",
            "2. high": "102.0100",
            "3. low": "100.5600",
            "4. close": "100.8500",
            "5. volume": "29492875"
        },
        "2018-06-14": {
            "1. open": "101.6500",
            "2. high": "102.0300",
            "3. low": "101.0000",
            "4. close": "101.4200",
            "5. volume": "25691811"
        },
        "2018-06-15": {
            "1. open": "101.5100",
            "2. high": "101.5300",
            "3. low": "100.0700",
            "4. close": "100.1300",
            "5. volume": "65738585"
        },
        "2018-06-18": {
            "1. open": "100.0100",
            "2. high": "101.1100",
            "3. low": "99.4200",
            "4. close": "100.8600",
            "5. volume": "23586037"
        },
        "2018-06-19": {
            "1. open": "99.6500",
            "2. high": "101.0000",
            "3. low": "99.5000",
            "4. close": "100.8600",
            "5. volume": "28653087"
        },
        "2018-06-20": {
            "1. open": "101.3700",
            "2. high": "102.5200",
            "3. low": "101.1200",
            "4. close": "101.8700",
            "5. volume": "26180792"
        },
        "2018-06-21": {
            "1. open": "102.0750",
            "2. high": "102.4600",
            "3. low": "100.8800",
            "4. close": "101.1400",
            "5. volume": "23198188"
        },
        "2018-06-22": {
            "1. open": "100.4100",
            "2. high": "100.7700",
            "3. low": "99.6250",
            "4. close": "100.4100",
            "5. volume": "38923105"
        },
        "2018-06-25": {
            "1. open": "100.0000",
            "2. high": "100.1100",
            "3. low": "97.3000",
            "4. close": "98.3900",
            "5. volume": "35433333"
        },
        "2018-06-26": {
            "1. open": "98.8200",
            "2. high": "100.0800",
            "3. low": "98.7500",
            "4. close": "99.0800",
            "5. volume": "26897244"
        },
        "2018-06-27": {
            "1. open": "99.5800",
            "2. high": "100.0200",
            "3. low": "97.4000",
            "4. close": "97.5400",
            "5. volume": "31298386"
        },
        "2018-06-28": {
            "1. open": "97.3800",
            "2. high": "99.1100",
            "3. low": "97.2600",
            "4. close": "98.6300",
            "5. volume": "26650671"
        },
        "2018-06-29": {
            "1. open": "98.9300",
            "2. high": "99.9100",
            "3. low": "98.3300",
            "4. close": "98.6100",
            "5. volume": "28053214"
        },
        "2018-07-02": {
            "1. open": "98.1000",
            "2. high": "100.0600",
            "3. low": "98.0000",
            "4. close": "100.0100",
            "5. volume": "19564521"
        },
        "2018-07-03": {
            "1. open": "100.4800",
            "2. high": "100.6300",
            "3. low": "98.9400",
            "4. close": "99.0500",
            "5. volume": "14670275"
        },
        "2018-07-05": {
            "1. open": "99.5000",
            "2. high": "99.9200",
            "3. low": "99.0299",
            "4. close": "99.7600",
            "5. volume": "18977402"
        },
        "2018-07-06": {
            "1. open": "99.8850",
            "2. high": "101.4300",
            "3. low": "99.6700",
            "4. close": "101.1600",
            "5. volume": "19234627"
        },
        "2018-07-09": {
            "1. open": "101.6452",
            "2. high": "102.2500",
            "3. low": "101.2510",
            "4. close": "101.8500",
            "5. volume": "18211980"
        },
        "2018-07-10": {
            "1. open": "102.0000",
            "2. high": "102.5100",
            "3. low": "101.8600",
            "4. close": "102.1200",
            "5. volume": "19293140"
        },
        "2018-07-11": {
            "1. open": "101.1500",
            "2. high": "102.3400",
            "3. low": "101.1000",
            "4. close": "101.9800",
            "5. volume": "19644648"
        },
        "2018-07-12": {
            "1. open": "102.7700",
            "2. high": "104.4100",
            "3. low": "102.7300",
            "4. close": "104.1900",
            "5. volume": "24335929"
        },
        "2018-07-13": {
            "1. open": "104.3700",
            "2. high": "105.6000",
            "3. low": "104.0900",
            "4. close": "105.4300",
            "5. volume": "24653500"
        },
        "2018-07-16": {
            "1. open": "105.4000",
            "2. high": "105.8200",
            "3. low": "104.5150",
            "4. close": "104.9100",
            "5. volume": "21786912"
        },
        "2018-07-17": {
            "1. open": "104.6100",
            "2. high": "106.5000",
            "3. low": "104.3200",
            "4. close": "105.9500",
            "5. volume": "25901726"
        },
        "2018-07-18": {
            "1. open": "105.9400",
            "2. high": "106.0500",
            "3. low": "104.7150",
            "4. close": "105.1200",
            "5. volume": "29493927"
        },
        "2018-07-19": {
            "1. open": "104.9300",
            "2. high": "105.3100",
            "3. low": "103.8900",
            "4. close": "104.4000",
            "5. volume": "40171646"
        },
        "2018-07-20": {
            "1. open": "108.0800",
            "2. high": "108.2000",
            "3. low": "106.0800",
            "4. close": "106.2700",
            "5. volume": "56038827"
        },
        "2018-07-23": {
            "1. open": "106.3000",
            "2. high": "108.1400",
            "3. low": "106.1300",
            "4. close": "107.9700",
            "5. volume": "29706955"
        },
        "2018-07-24": {
            "1. open": "108.5700",
            "2. high": "108.8200",
            "3. low": "107.2600",
            "4. close": "107.6600",
            "5. volume": "26316619"
        },
        "2018-07-25": {
            "1. open": "107.9550",
            "2. high": "111.1500",
            "3. low": "107.6000",
            "4. close": "110.8300",
            "5. volume": "30798058"
        },
        "2018-07-26": {
            "1. open": "110.7400",
            "2. high": "111.0000",
            "3. low": "109.5000",
            "4. close": "109.6200",
            "5. volume": "31372110"
        },
        "2018-07-27": {
            "1. open": "110.1800",
            "2. high": "110.1800",
            "3. low": "106.1400",
            "4. close": "107.6800",
            "5. volume": "37005292"
        },
        "2018-07-30": {
            "1. open": "107.1900",
            "2. high": "107.5300",
            "3. low": "104.7600",
            "4. close": "105.3700",
            "5. volume": "34668327"
        },
        "2018-07-31": {
            "1. open": "106.4900",
            "2. high": "106.7200",
            "3. low": "105.3800",
            "4. close": "106.0800",
            "5. volume": "27655152"
        },
        "2018-08-01": {
            "1. open": "106.0300",
            "2. high": "106.4460",
            "3. low": "105.4200",
            "4. close": "106.2800",
            "5. volume": "23628699"
        },
        "2018-08-02": {
            "1. open": "105.4000",
            "2. high": "108.0900",
            "3. low": "104.8400",
            "4. close": "107.5700",
            "5. volume": "26104258"
        },
        "2018-08-03": {
            "1. open": "107.8000",
            "2. high": "108.0500",
            "3. low": "106.8200",
            "4. close": "108.0400",
            "5. volume": "18659599"
        },
        "2018-08-06": {
            "1. open": "108.1200",
            "2. high": "108.4200",
            "3. low": "107.5590",
            "4. close": "108.1300",
            "5. volume": "20265947"
        },
        "2018-08-07": {
            "1. open": "108.5600",
            "2. high": "109.1000",
            "3. low": "108.1700",
            "4. close": "108.8800",
            "5. volume": "16080214"
        },
        "2018-08-08": {
            "1. open": "109.3300",
            "2. high": "109.7500",
            "3. low": "108.7599",
            "4. close": "109.4900",
            "5. volume": "15487502"
        },
        "2018-08-09": {
            "1. open": "109.7100",
            "2. high": "110.1600",
            "3. low": "109.6000",
            "4. close": "109.6700",
            "5. volume": "13677211"
        },
        "2018-08-10": {
            "1. open": "109.4200",
            "2. high": "109.6900",
            "3. low": "108.3800",
            "4. close": "109.0000",
            "5. volume": "18183724"
        },
        "2018-08-13": {
            "1. open": "109.2400",
            "2. high": "109.5800",
            "3. low": "108.1000",
            "4. close": "108.2100",
            "5. volume": "18474884"
        },
        "2018-08-14": {
            "1. open": "108.5600",
            "2. high": "109.7500",
            "3. low": "108.0400",
            "4. close": "109.5600",
            "5. volume": "16788314"
        },
        "2018-08-15": {
            "1. open": "108.4900",
            "2. high": "108.9850",
            "3. low": "106.8200",
            "4. close": "107.6600",
            "5. volume": "29982806"
        },
        "2018-08-16": {
            "1. open": "108.3000",
            "2. high": "108.8600",
            "3. low": "107.3000",
            "4. close": "107.6400",
            "5. volume": "21384289"
        },
        "2018-08-17": {
            "1. open": "107.3600",
            "2. high": "107.9000",
            "3. low": "106.6900",
            "4. close": "107.5800",
            "5. volume": "18061512"
        },
        "2018-08-20": {
            "1. open": "107.5100",
            "2. high": "107.9000",
            "3. low": "106.4800",
            "4. close": "106.8700",
            "5. volume": "17914201"
        },
        "2018-08-21": {
            "1. open": "106.9200",
            "2. high": "107.3500",
            "3. low": "105.8500",
            "4. close": "105.9800",
            "5. volume": "22881861"
        },
        "2018-08-22": {
            "1. open": "105.8500",
            "2. high": "107.3400",
            "3. low": "105.7800",
            "4. close": "107.0600",
            "5. volume": "18000639"
        },
        "2018-08-23": {

In [9]:
# set dates
stock_dates = []

start_date = datetime.date(2018,4,10)

for i in range(142):
    stock_date = start_date + datetime.timedelta(i)
    stock_dates.append(stock_date.isoformat())

In [13]:
high_prices = []
low_prices = []
open_prices = []
close_prices = []
volume_shares = []
dates = []

for stock_date in stock_dates:
    try:
        open_prices.append(stock_data["Time Series (Daily)"][stock_date]["1. open"])
        high_prices.append(stock_data["Time Series (Daily)"][stock_date]["2. high"])
        low_prices.append(stock_data["Time Series (Daily)"][stock_date]["3. low"])
        close_prices.append(stock_data["Time Series (Daily)"][stock_date]["4. close"])
        volume_shares.append(stock_data["Time Series (Daily)"][stock_date]["5. volume"])
        if stock_date in stock_data["Time Series (Daily)"].keys():
            dates.append(stock_date)
    except:
        pass

In [14]:
Stock_Data = pd.DataFrame({"Date":dates,
                           "S&P Open Price": open_prices,
                           "S&P Low Price": low_prices,
                           "S&P High Prices": high_prices,
                           "S&P Close Price": close_prices,
                           "S&P Volume": volume_shares})

In [15]:
Stock_Data

,Date,S&P Open Price,S&P Low Price,S&P High Prices,S&P Close Price,S&P Volume
0,2018-04-11,92.0100,91.4800,93.2900,91.8600,24872110
1,2018-04-12,92.4300,92.4300,94.1600,93.5800,26758879
2,2018-04-13,94.0500,92.4400,94.1800,93.0800,23346063
3,2018-04-16,94.0700,93.4200,94.6600,94.1700,20288083
4,2018-04-17,95.0000,94.8800,96.5400,96.0700,26771000
5,2018-04-18,96.2200,95.5200,96.7200,96.4400,21043287
6,2018-04-19,96.4400,95.3400,97.0700,96.1100,23552541
7,2018-04-20,95.9100,94.0500,96.1100,95.0000,31154377
8,2018-04-23,95.7436,94.6300,96.2900,95.3500,22331829
9,2018-04-24,96.2420,92.4100,96.4700,93.1200,34524799
10,2018-04-25,93.3000,90.2800,93.3000,92.3100,33729257
11,2018-04-26,93.5500,93.1000,95.1500,94.2600,42529043
12,2018-04-27,97.6000,93.9100,97.9000,95.8200,48272780
13,2018-04-30,96.3300,93.1500,96.3964,93.5200,41523605
14,2018-05-01,93.2100,92.7900,95.2900,95.0000,31408927
15,2018-05-02,94.9900,93.1900,95.1700,93.5100,27471002
16,2018-05-03,92.9600,92.4500,94.9250,94.0700,31142497
17,2018-05-04,93.3200,92.9200,95.3700,95.1600,22531325
18,2018-05-07,95.1700,95.1000,96.7100,96.2200,24242019
19,2018-05-08,95.8456,95.0631,96.1600,95.8100,23484589
20,2018-05-09,96.0100,95.0500,96.9700,96.9400,27327410
21,2018-05-10,97.4600,97.0500,97.9500,97.9100,22388119
22,2018-05-11,97.8000,97.0400,97.8700,97.7000,16778316
23,2018-05-14,97.9200,97.3100,98.6900,98.0300,19454124
24,2018-05-15,97.2400,96.3400,97.8500,97.3200,24594010
25,2018-05-16,97.3600,96.6150,97.4000,97.1500,17384742
26,2018-05-17,96.7600,95.8300,97.5401,96.1800,17246716
27,2018-05-18,96.0100,96.0100,96.9300,96.3600,17865840
28,2018-05-21,97.0000,96.8000,98.0100,97.6000,19422467
29,2018-05-22,97.6800,97.2000,98.1700,97.5000,15441189
...,...,...,...,...,...,...
69,2018-07-19,104.9300,103.8900,105.3100,104.4000,40171646
70,2018-07-20,108.0800,106.0800,108.2000,106.2700,56038827
71,2018-07-23,106.3000,106.1300,108.1400,107.9700,29706955
72,2018-07-24,108.5700,107.2600,108.8200,107.6600,26316619
73,2018-07-25,107.9550,107.6000,111.1500,110.8300,30798058
74,2018-07-26,110.7400,109.5000,111.0000,109.6200,31372110
75,2018-07-27,110.1800,106.1400,110.1800,107.6800,37005292
76,2018-07-30,107.1900,104.7600,107.5300,105.3700,34668327
77,2018-07-31,106.4900,105.3800,106.7200,106.0800,27655152
78,2018-08-01,106.0300,105.4200,106.4460,106.2800,23628699
79,2018-08-02,105.4000,104.8400,108.0900,107.5700,26104258
80,2018-08-03,107.8000,106.8200,108.0500,108.0400,18659599
81,2018-08-06,108.1200,107.5590,108.4200,108.1300,20265947
82,2018-08-07,108.5600,108.1700,109.1000,108.8800,16080214
83,2018-08-08,109.3300,108.7599,109.7500,109.4900,15487502
84,2018-08-09,109.7100,109.6000,110.1600,109.6700,13677211
85,2018-08-10,109.4200,108.3800,109.6900,109.0000,18183724
86,2018-08-13,109.2400,108.1000,109.5800,108.2100,18474884
87,2018-08-14,108.5600,108.0400,109.7500,109.5600,16788314
88,2018-08-15,108.4900,106.8200,108.9850,107.6600,29982806
89,2018-08-16,108.3000,107.3000,108.8600,107.6400,21384289
90,2018-08-17,107.3600,106.6900,107.9000,107.5800,18061512
91,2018-08-20,107.5100,106.4800,107.9000,106.8700,17914201
92,2018-08-21,106.9200,105.8500,107.3500,105.9800,22881861
93,2018-08-22,105.8500,105.7800,107.3400,107.0600,18000639
94,2018-08-23,107.1500,106.8700,108.1800,107.5600,18167723
95,2018-08-24,107.6700,107.5600,108.5600,108.4000,17234020
96,2018-08-27,109.2700,108.5100,109.6400,109.6000,19662331
97,2018-08-28,109.9400,109.7900,110.5000,110.2600,19151528
98,2018-08-29,110.4500,110.2700,112.0300,112.0200,20747002

## New York Times

In [24]:
from nytimes import api_key

In [25]:
url = "https://api.nytimes.com/svc/search/v2/articlesearch.json"

n = 200
pages = range(n)
snippet = []
pub_date = []


for page in pages:
    params = {
    "api_key" : api_key,
    "q" : "apple",
    "begin_data" : "20180410",
    "end_data" : "20180829",
    "fl": ["snippet","pub_date"],
    "page": page
}
    try:
        nyt_data = req.get(url, params=params).json()
        for i in range(10):
            snippet.append(nyt_data["response"]["docs"][i]["snippet"])
            pub_date.append(nyt_data["response"]["docs"][i]["pub_date"][:10])
    except:
        pass

In [28]:
nyt_data = req.get(url, params=params).json()

In [29]:
analyzer = SentimentIntensityAnalyzer()
sentences = snippet
vader_scores = []
date_nyt = []

for sentence in sentences:
    snt = analyzer.polarity_scores(sentence)
    vader_scores.append(snt["compound"])
    date_nyt.append(pub_date)

In [30]:
Nyt_Data = pd.DataFrame({"Date": date_nyt,
                         "Nyt_VaderScore": vader_scores})

In [31]:
Nyt_Data

                                                  Date  Nyt_VaderScore
0    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.8100
1    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4215
2    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3291
3    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
4    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.7579
5    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.7906
6    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
7    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2960
8    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3182
9    [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.5859
10   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
11   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2263
12   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.1531
13   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.1655
14   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.9403
15   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
16   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
17   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
18   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
19   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
20   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2960
21   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2960
22   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
23   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4215
24   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3400
25   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.2960
26   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2732
27   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
28   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3612
29   [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4404
..                                                 ...             ...
592  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
593  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4019
594  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.5719
595  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.1779
596  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.1280
597  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.6705
598  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.8555
599  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3400
600  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4019
601  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.5423
602  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
603  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.8481
604  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.6249
605  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
606  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
607  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0772
608  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.3182
609  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
610  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
611  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0772
612  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.4404
613  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
614  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.7717
615  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
616  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
617  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.0516
618  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.6705
619  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.0000
620  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...          0.2382
621  [2018-08-06, 2018-06-06, 2018-08-28, 2018-08-2...         -0.2732

[622 rows x 2 columns]

## CNN

In [ ]:
from cnn import api_key

In [ ]:
cnn_url = "https://newsapi.org/v2/everything?sources=cnn&apiKey=fc8819e4d99247a589aa9a4ca8f649c8"

In [ ]:
params = {
    "q" : "apple",
    "begin_data" : "20180410",
    "end_data" : "20180829",
    "date":"YYYY-MM-DD"
}

In [ ]:
cnn_data = req.get(cnn_url, params=params).json()

In [ ]:
cnn_data

In [ ]:
cnn_data["articles"][0]["description"]

In [ ]:
new_date=dateExampl.split("T")[0]

In [ ]:
new_date

In [ ]:
publishedAt = []
description = []
n = 0
for i in cnn_data:
    try:
        publishedAt.append(cnn_data["articles"][0]["publishedAt"])
        description.append(cnn_data["articles"][0]['description'])
        n= n+1
    except:
        pass

In [ ]:
description

In [ ]:
description = []
dates = dates


for date in dates:
    description.append(cnn_data["articles"][0]["description"])

In [ ]:
sentences = description
vader_scores_cnn = []

for sentence in sentences:
    snt = analyzer.polarity_scores(sentence)
    vader_scores_cnn.append(snt["compound"])

In [ ]:
CNN_Data = pd.DataFrame({"Date": dates,
                         "Cnn_VaderScore": vader_scores_cnn})

In [ ]:
CNN_Data

## FOX NEWS

In [ ]:
from fox import api_key

In [ ]:
fox_url = "https://newsapi.org/v2/everything?sources=fox-news&apiKey=fc8819e4d99247a589aa9a4ca8f649c8"

In [ ]:
params = {
    "q" : "apple",
    "begin_data" : "20180410",
    "end_data" : "20180829",
    "date":"YYYY-MM-DD"
}

In [ ]:
fox_data=req.get(fox_url, params=params).json()

In [ ]:
print(json.dumps(fox_data, indent=4, sort_keys=True))

In [ ]:
fox_data["articles"][0]["description"]

In [ ]:
description = []
dates = dates


for date in dates:
    description.append(fox_data["articles"][0]["description"])

In [ ]:
sentences = description
vader_scores_fox = []

for sentence in sentences:
    snt = analyzer.polarity_scores(sentence)
    vader_scores_fox.append(snt["compound"])

In [ ]:
Fox_Data = pd.DataFrame({"Date": dates,
                         "Fox_VaderScore": vader_scores_fox})

In [ ]:
Fox_Data

## THE WALL STREET JOURNAL API

In [ ]:
from wsj import api_key

In [ ]:
wsj_url = "https://newsapi.org/v2/everything?sources=the-wall-street-journal&apiKey=fc8819e4d99247a589aa9a4ca8f649c8"

In [ ]:
params = {
    #"api_key" : api_key,
    "q" : "apple",
    "begin_data" : "20180410",
    "end_data" : "20180829",
    "date":"YYYY-MM-DD"
    #"page":100
}

In [ ]:
wsj_url

In [ ]:
analyzer = SentimentIntensityAnalyzer()

In [ ]:
wsj_data=req.get(wsj_url, params=params).json()

In [ ]:
print(json.dumps(wsj_data, indent=4, sort_keys=True))

In [ ]:
wsj_data["articles"][0]["description"]

In [ ]:
description = []
dates = dates


for date in dates:
    description.append(wsj_data["articles"][0]["description"])

In [ ]:
description

In [ ]:
sentences = description
vader_scores_wsj = []

for sentence in sentences:
    snt = analyzer.polarity_scores(sentence)
    vader_scores_wsj.append(snt["compound"])

In [ ]:
Wsj_Data = pd.DataFrame({"Date": dates,
                         "Wsj_VaderScore": vader_scores_wsj})

In [ ]:
Wsj_Data

## Merged all data

In [ ]:
# merged Nyt_Data and CNN_Data on Date
Nyt_CNN = pd.merge(Nyt_Data, CNN_Data, on="Date", how="inner")
# merged Fox_Data and Wsj_Data on Date
Fox_Wsj = pd.merge(Fox_Data, Wsj_Data, on="Date", how="inner")
# merge again the above two merged data (Nyt_CNN and Fox_Wsj)
Nyt_CNN_Fox_Wsj = pd.merge(Nyt_CNN, Fox_Wsj, on="Date", how="inner")

In [ ]:
Nyt_CNN_Fox_Wsj

In [ ]:
#Lastly this merged with stock data
STOCK_DATA = pd.merge(Stock_Data, Nyt_CNN_Fox_Wsj, on="Date", how="inner")

In [ ]:
STOCK_DATA